// for loop
for(let i=0; i<5; i++){
    console.log("namasteee");
}
//for addition:multiple perameter
function sum(a,b)
{
 sum=a+b;
 return sum;
}
let finalresult=sum(5,6);
let ratim=5-finalresult;
console.log(ratim);

//for name:single perameter

function greed(name)//function declation
{
    console.log("hello"+name);// function defination:
}
greed("rupak");//argment:funtion call
/// for more:
function intro(name,age,city)
{
    console.log("hello"+name+" you are "+age+" years old and live in "+city);
}
intro("rupak",25,"delhi");
